name: "coarse-only"
device: "cuda:0"
data:
  xray_dir: "test"
  source_ct_path: "nrrd/2 AC_CT_TBody.nrrd"
  num_workers: 8
  pin_memory: True
checkpoint:
  # checkpoint_dir: "coarse-only/20241020-172736"
  checkpoint_interval: 1
  resume_epoch: 1
model:
  n_layers: 8
  layer_dim: 256
  L: 20
training:
  lr: 0.0001
  batch_size: 4096
  num_coarse_samples: 64
  num_fine_samples: 64
  dtype: "float32"
  use_amp: True
scaling:
  s: 1
  k: 0.1